apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: {{ template "app.fullname" . }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ template "app.fullname" . }}
  minReplicas: {{ .Values.horizontalScaling.minReplicas }}
  maxReplicas: {{ .Values.horizontalScaling.maxReplicas }}
  targetCPUUtilizationPercentage: 75